# Generated by Django 6.0.7 on 2026-08-03 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(db_index=True, max_length=50, unique=True)),
                ('imei2', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('meid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('model', models.CharField(db_index=True, help_text='e.g. iPhone 15 Pro Max', max_length=150)),
                ('model_description', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_country', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_policy', models.CharField(blank=True, max_length=150, null=True)),
                ('sim_lock_status', models.CharField(blank=True, max_length=100, null=True)),
                ('icloud_status', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_status', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_purchase_date', models.DateField(blank=True, null=True)),
                ('demo_unit', models.BooleanField(default=False)),
                ('loaner_device', models.BooleanField(default=False)),
                ('replacement_device', models.BooleanField(default=False)),
                ('replaced_device', models.BooleanField(default=False)),
                ('refurbished', models.BooleanField(default=False)),
                ('battery_health', models.PositiveIntegerField(blank=True, help_text='Percentage e.g. 95', null=True)),
                ('battery_cycle', models.PositiveIntegerField(blank=True, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100, null=True)),
                ('face_id', models.CharField(blank=True, default='Working', max_length=50, null=True)),
                ('true_tone', models.CharField(blank=True, default='Working', max_length=50, null=True)),
                ('original_parts_status', models.CharField(blank=True, max_length=150, null=True)),
                ('variant', models.CharField(blank=True, help_text='Region variant e.g. LL/A, ZA/A', max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_STOCK', 'In Stock'), ('RESERVED', 'Reserved'), ('ASSIGNED', 'Assigned'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('UNDER_REPAIR', 'Under Repair'), ('SENT_TO_CHINA', 'Sent To China'), ('WAITING_SHIPMENT', 'Waiting Shipment'), ('DISPOSED', 'Disposed'), ('LOST', 'Lost')], db_index=True, default='RECEIVED', max_length=30)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
                ('current_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarrierInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lock_status', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_details', models.TextField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_info', to='inventory.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(max_length=50)),
                ('old_state', models.TextField(blank=True, null=True)),
                ('new_state', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_notes', to='inventory.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_type', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('DISPLAY', 'Display'), ('BATTERY', 'Battery'), ('IMEI_STICKER', 'IMEI Sticker'), ('REPAIR', 'Repair Photo'), ('INVOICE', 'Invoice'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='FRONT', max_length=30)),
                ('image', models.ImageField(upload_to='device_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='Apple Care', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('claim_status', models.CharField(default='Active', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='inventory.device')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
