# Generated by Django 6.1 on 2026-08-07 23:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total buying cost price (Item price + Shipment fees) in BDT', max_digits=12),
        ),
    ]
