# Generated by Django 6.1 on 2026-08-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_device_buying_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_status',
            field=models.CharField(choices=[('WAITING_SHIPMENT', 'Waiting Shipment'), ('IN_STOCK', 'In Stock'), ('ASSIGNED', 'Assigned'), ('UNDER_REPAIR', 'Under Repair'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('LOST', 'Lost')], db_index=True, default='WAITING_SHIPMENT', max_length=30),
        ),
    ]
