# Generated by Django 6.1 on 2026-09-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_device_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='variant',
            field=models.CharField(blank=True, choices=[('Modified', 'Modified'), ('USA eSim', 'USA eSim'), ('Canada', 'Canada'), ('Mexican', 'Mexican'), ('Korea', 'Korea'), ('Singapore', 'Singapore'), ('Bypass', 'Bypass')], help_text='Device variant', max_length=50, null=True),
        ),
    ]
