# Generated by Django 6.1 on 2026-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_normalize_assigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='received_date_bd',
            field=models.DateField(blank=True, help_text='Date device was physically received in Bangladesh', null=True),
        ),
    ]
