# Generated by Django 6.0.7 on 2026-08-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickwReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_text', models.TextField(help_text='Original unedited Sickw output block')),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('model_description', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('imei2', models.CharField(blank=True, max_length=50, null=True)),
                ('meid', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_purchase_date', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_status', models.CharField(blank=True, max_length=150, null=True)),
                ('icloud_lock', models.CharField(blank=True, max_length=100, null=True)),
                ('demo_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('loaner_device', models.CharField(blank=True, max_length=50, null=True)),
                ('replaced_device', models.CharField(blank=True, max_length=50, null=True)),
                ('replacement_device', models.CharField(blank=True, max_length=50, null=True)),
                ('refurbished_device', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_country', models.CharField(blank=True, max_length=100, null=True)),
                ('locked_carrier', models.CharField(blank=True, max_length=150, null=True)),
                ('sim_lock_status', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sickw_reports', to='inventory.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
