# Generated by Django 6.1 on 2026-08-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
