# Generated by Django 6.1 on 2026-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cashback or discount from shipping agent in BDT', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gross total shipping cost in BDT', max_digits=12),
        ),
    ]
