# Generated by Django 6.0.7 on 2026-08-03 19:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price of device', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Agreed sale price', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Selling price - Discount - Buying price', max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending')], default='PAID', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Credit/Debit Card'), ('MOBILE', 'Mobile Banking')], default='CASH', max_length=20)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.device')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
    ]
