# Generated by Django 6.1 on 2026-08-07 23:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employee commission amount in BDT', max_digits=12),
        ),
    ]
