# Generated by Django 6.1 on 2026-09-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_device_current_status'),
        ('sales', '0003_alter_sale_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSaleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Proposed or expected selling price in BDT', max_digits=12, null=True)),
                ('payment_method', models.CharField(default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('confirmed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Admin confirmed selling price in BDT', max_digits=12, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_requests', to='inventory.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_sale_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sale_requests', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
